// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ-fgHX4GXTemsgJwpnDk1d2_Ek7Ni0uU',
    appId: '1:833586579373:web:ee6f65dd132f8eeaa14324',
    messagingSenderId: '833586579373',
    projectId: 'my-project-433d3',
    authDomain: 'my-project-433d3.firebaseapp.com',
    storageBucket: 'my-project-433d3.firebasestorage.app',
    measurementId: 'G-CS051NV4XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ8DOF0OHup0tZY8NGjjtjb-IRmYj0hB0',
    appId: '1:833586579373:android:588a150c759ea179a14324',
    messagingSenderId: '833586579373',
    projectId: 'my-project-433d3',
    storageBucket: 'my-project-433d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeMI4eCZv46XMjbq7k_Xq7RO2by3ijjUE',
    appId: '1:833586579373:ios:70848349a7c338e4a14324',
    messagingSenderId: '833586579373',
    projectId: 'my-project-433d3',
    storageBucket: 'my-project-433d3.firebasestorage.app',
    iosBundleId: 'com.example.myBarishalNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeMI4eCZv46XMjbq7k_Xq7RO2by3ijjUE',
    appId: '1:833586579373:ios:70848349a7c338e4a14324',
    messagingSenderId: '833586579373',
    projectId: 'my-project-433d3',
    storageBucket: 'my-project-433d3.firebasestorage.app',
    iosBundleId: 'com.example.myBarishalNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ-fgHX4GXTemsgJwpnDk1d2_Ek7Ni0uU',
    appId: '1:833586579373:web:4d9f3202d622e72aa14324',
    messagingSenderId: '833586579373',
    projectId: 'my-project-433d3',
    authDomain: 'my-project-433d3.firebaseapp.com',
    storageBucket: 'my-project-433d3.firebasestorage.app',
    measurementId: 'G-16T2Q306CS',
  );

}