// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkO2jr6sJogtlXEw42ud0RGVxp2b1yyqY',
    appId: '1:1003589281276:web:91ad84af4afc163035be79',
    messagingSenderId: '1003589281276',
    projectId: 'my-barishal-new',
    authDomain: 'my-barishal-new.firebaseapp.com',
    storageBucket: 'my-barishal-new.firebasestorage.app',
    measurementId: 'G-SPMXYS6L0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1w6r4YeNWsGFMEInFD71CzkXgDJdoNRU',
    appId: '1:1003589281276:android:6ca5209ce0229c6935be79',
    messagingSenderId: '1003589281276',
    projectId: 'my-barishal-new',
    storageBucket: 'my-barishal-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2VaI9liCuGCbfECpG4eK5IXBTHhEQg1E',
    appId: '1:1003589281276:ios:a66ee8be348f09e935be79',
    messagingSenderId: '1003589281276',
    projectId: 'my-barishal-new',
    storageBucket: 'my-barishal-new.firebasestorage.app',
    iosBundleId: 'com.example.myBarishalNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2VaI9liCuGCbfECpG4eK5IXBTHhEQg1E',
    appId: '1:1003589281276:ios:a66ee8be348f09e935be79',
    messagingSenderId: '1003589281276',
    projectId: 'my-barishal-new',
    storageBucket: 'my-barishal-new.firebasestorage.app',
    iosBundleId: 'com.example.myBarishalNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkO2jr6sJogtlXEw42ud0RGVxp2b1yyqY',
    appId: '1:1003589281276:web:62f5cfb0b42a13b535be79',
    messagingSenderId: '1003589281276',
    projectId: 'my-barishal-new',
    authDomain: 'my-barishal-new.firebaseapp.com',
    storageBucket: 'my-barishal-new.firebasestorage.app',
    measurementId: 'G-1YM9XHPT1G',
  );
}
